apiVersion: v1
kind: Service
metadata:
  name: using-external-ip-default
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: using-external-ip-explicit
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  externalIPs:
    - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: using-external-ip-allowed
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  externalIPs:
---
apiVersion: v1
kind: Service
metadata:
  name: using-external-ip-allowed-2
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: using-external-ip-nodeport-allowed
spec:
  selector:
    app: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  externalIPs:
    - 1.1.1.1